@server_url = http://192.168.1.120:8080

###
GET {{server_url}}/nodes HTTP/1.1

###
GET {{server_url}}/node/0 HTTP/1.1

###
GET {{server_url}}/node_with_nest/40 HTTP/1.1

###
POST {{server_url}}/create_node HTTP/1.1
content-type: application/json

{
    "parrent_id": 95,
    "node_name": "Првпacаптрапкукпивет"
}
###
POST {{server_url}}/drop_node/102 HTTP/1.1


###
POST {{server_url}}/create_street HTTP/1.1
content-type: application/json

{
    "node_id": 19,
    "street_name": "Букетова"
}


###
GET {{server_url}}/get_streets/778d1c3b-cf00-438d-bc31-095f991e2247 HTTP/1.1

###
GET {{server_url}}/get_buildings/1 HTTP/1.1


###
POST {{server_url}}/update_name HTTP/1.1
content-type: application/json

{
    "node_id": 67, 
    "object":"NODE",  
    "name": "yyyyyyyyyyyyy"
}