[package]
name = "docx_table_parser"
version = "0.1.0"
edition = "2021"

[workspace]

members = ["axum_server"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
docx-rs = "0.4"

serde_json = "1"
serde = { version = "1", features = ["derive"] }
